USE [HYT]

GO

SET ANSI_PADDING ON


GO
-- Index Phần của Huy
CREATE NONCLUSTERED INDEX [LSN_All_index] ON [dbo].[LICHSUNHAP]
(
	[NGAYNHAP],[MASP]
)
GO
CREATE NONCLUSTERED INDEX [LSX_MaSP_index] ON [dbo].[CT_DONHANG]
(
	[MASP] ASC
)
GO
CREATE NONCLUSTERED INDEX [LSX_MaDH_index] ON [dbo].[CT_DONHANG]
(
	[MADH] ASC
)
GO
CREATE NONCLUSTERED INDEX [LSX_NgayXuat_index] ON [dbo].[DONHANG]
(
	[NGAYLAP] ASC
)

-- Index Phần của Đức
CREATE NONCLUSTERED INDEX [TimKiemSP_index] ON [dbo].[SANPHAM]
(
	[THANHPHANCHINH] ASC
)
